### ISSUE TITLE
code in musegan.ipynb

### ISSUE THREAD

**Issue by MandyLiuu** [salu133445/ismir2019tutorial#2]
Hi @salu133445 Thank you for useful repo !

When I try musegan.ipynb in `Settings `part , I found that the program number for each track is `programs = [0, 0, 25, 33, 48]`, `track_names = ['Drums', 'Piano', 'Guitar', 'Bass', 'Strings']`. Is the program number of the drum wrong, or did I miss something?

**Comment by salu133445** [comment]
The program numbers are for creating MIDI samples. In MIDI, drums have a dedicated channel and program numbers have no effect for drums.

**Comment by MandyLiuu** [comment]
> The program numbers are for creating MIDI samples. In MIDI, drums have a dedicated channel and program numbers have no effect for drums.

Got that, thank you.
